# Generated by Django 4.1.3 on 2022-11-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_domain', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=150)),
                ('organization_mail_server', models.CharField(max_length=150)),
            ],
        ),
    ]
