# Generated by Django 4.1.3 on 2022-11-26 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bms_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=150)),
                ('department_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms_base.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('member_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms_base.department')),
                ('member_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
