# Generated by Django 4.1.3 on 2022-11-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_base', '0002_department_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='member',
            name='member_date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
