# Generated by Django 4.1.3 on 2022-11-28 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bms_base', '0003_department_department_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
