# Generated by Django 4.1.3 on 2022-12-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_base', '0005_department_department_mail_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_recruting',
            field=models.BooleanField(default=False),
        ),
    ]
