# Generated by Django 4.1.3 on 2022-12-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_base', '0006_department_department_recruting'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
