# Generated by Django 4.1.3 on 2022-11-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailEngine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='flag_prominence',
            field=models.IntegerField(null=True),
        ),
    ]
