# Generated by Django 4.1.3 on 2022-11-29 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailEngine', '0002_flag_flag_prominence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailobject',
            name='user_account',
        ),
        migrations.AddField(
            model_name='flag',
            name='mail_box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mailEngine.mailbox'),
        ),
    ]
