# Generated by Django 4.1.3 on 2022-11-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailEngine', '0003_remove_mailobject_user_account_flag_mail_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailattachment',
            name='file_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mailattachment',
            name='file_type',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
