# Generated by Django 4.1.3 on 2022-11-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailEngine', '0004_mailattachment_file_name_mailattachment_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailattachment',
            name='file_extension',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
