# Generated by Django 4.1.3 on 2022-11-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailEngine', '0005_mailattachment_file_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='flag_imap_label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
