# Generated by Django 4.1.3 on 2022-11-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailEngine', '0006_flag_flag_imap_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='mail_number',
            field=models.IntegerField(default=0),
        ),
    ]
