# Generated by Django 4.1.3 on 2022-12-01 00:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailEngine', '0007_flag_mail_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailhead',
            name='mail_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
