# Generated by Django 4.1.3 on 2022-12-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailEngine', '0008_alter_mailhead_mail_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailhead',
            name='mail_server_id',
            field=models.IntegerField(null=True),
        ),
    ]
