# Generated by Django 4.1.3 on 2022-12-03 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailEngine', '0009_mailhead_mail_server_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailhead',
            name='mail_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mailEngine.mailaccount'),
        ),
    ]
