# Generated by Django 4.1.3 on 2022-12-03 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailEngine', '0010_mailhead_mail_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='account_mails',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='label_flag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mailEngine.flag'),
        ),
    ]
